version: 1
objects:
  queue: dummy

formatters:
  simple:
    format: '%(time_filter)-15s: %(levelname)-.1s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

filters:
  time_filter:
    (): elliot.utils.logging.TimeFilter

handlers:
  console:
    class: logging.StreamHandler
    level: FATAL
    formatter: simple
    stream: ext://sys.stdout
    filters: [time_filter]

  file:
    class: logging.FileHandler
    level: FATAL
    filename: !CUSTOM ${log_path_exp}
    formatter: simple
    filters: [time_filter]

  queue_listener:
    class: elliot.utils.logger_util.QueueListenerHandler
    handlers:
      - console
      - file
    queue: null

loggers:
  'recommender':
    level: FATAL
    handlers: [queue_listener]
    propagate: false

  'DataSet':
    level: FATAL
    handlers: [queue_listener]

  'KnowledgeChainsLoader':
    level: FATAL
    handlers: [queue_listener]

  'KnowledgeChainsDataObject':
    level: FATAL
    handlers: [queue_listener]

  'VisualLoader':
    level: FATAL
    handlers: [queue_listener]

  'VisualDataObject':
    level: FATAL
    handlers: [queue_listener]

  'DataSetLoader':
    level: FATAL
    handlers: [queue_listener]

  'Evaluator':
    level: FATAL
    handlers: [queue_listener]

  'namespace':
    level: FATAL
    handlers: [queue_listener]

  'ModelCoordinator':
    level: FATAL
    handlers: [queue_listener]

  'prefiltering':
    level: FATAL
    handlers: [queue_listener]

  'splitter':
    level: FATAL
    handlers: [queue_listener]

  'result_handler':
    level: FATAL
    handlers: [queue_listener]

  'EarlyStopping':
    level: FATAL
    handlers: [queue_listener]

  __main__:
    level: FATAL
    handlers: [queue_listener]
    propagate: false

root:
  level: FATAL
  handlers:
    - console
